NB-694 Added new v4.2 endpoints
NeverBounce/NeverBounceApi-Go pull request #25
Opened 2020-07-20 17:52 UTC by georgenov

[NB-694](https://discoverorg.atlassian.net/browse/NB-694): Go

2020-07-20 17:52 UTC, georgenov commented
I should update examples with new params

2020-07-20 21:46 UTC, mmollick requested changes

2020-07-20 21:46 UTC, mmollick commented on models/jobs_create_model.go
> +	CallbackUrl       string                 `json:"callback_url,omitempty"`
Let's rename `CallbackUrl` to `CallbackURL`

2020-07-20 21:46 UTC, mmollick commented on models/jobs_create_model.go
> +	CallbackUrl       string                 `json:"callback_url,omitempty"`
Let's rename `CallbackUrl` to `CallbackURL`

2020-07-23 18:26 UTC, mmollick approved these changes

2020-08-05 15:44 UTC, mmollick approved these changes

2020-08-05 15:45 UTC, merged